# Generated by Django 3.1.2 on 2020-10-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cat_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cat_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cat_3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cat_4',
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='ord_item', through='orders.Order_Item', to='orders.Item'),
        ),
    ]
