# Generated by Django 3.1.2 on 2020-10-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201015_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='unit',
            field=models.CharField(default='No.s', max_length=10),
        ),
    ]
