# Generated by Django 3.1.2 on 2020-10-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_item_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='unit',
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default='No.s', max_length=10),
        ),
    ]
