# Generated by Django 3.1.2 on 2020-10-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('orders', '0011_auto_20201017_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='ord_item', through='orders.Order_Item', to='item.Item'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
