# Generated by Django 3.1.2 on 2020-11-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20201017_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
