# Generated by Django 3.1.2 on 2021-04-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20210403_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='piad',
            new_name='paid',
        ),
    ]
